### ISSUE TITLE
please upgrade logback to >= 1.1.8

### ISSUE THREAD

**Issue by koglinjg** [cambium-clojure/cambium.core#1]
logback 1.1.7 has this bug: https://jira.qos.ch/browse/LOGBACK-1166
https://github.com/cambium-clojure/cambium.core/blob/v0.9.1/project.clj#L15-L16

**Comment by kumarshantanu** [comment]
The [cambium.logback.core](https://github.com/cambium-clojure/cambium.logback.core) module (as of version 0.4.1) uses Logback 1.2.3:
https://github.com/cambium-clojure/cambium.logback.core/blob/v0.4.1/project.clj#L7-L8
