### ISSUE TITLE
arguments to log function

### ISSUE THREAD

**Issue by devn** [cambium-clojure/cambium.core#2]
I find the argument order to the log function to be a bit confusing. I'm wondering if there's a better way to handle all of the cases.

Right now the signatures are as follows:
```
level msg (2)
logger level msg (3)
level mdc throwable msg (4)
logger level mdc throwable msg (5)
```

It's somewhat confusing to see msg in the 2nd, 3rd, 4th, and 5th positions, mdc in the 2nd and 3rd positions, level in the 1st and 2nd positions, and throwable in the 3rd and 4th positions.

Perhaps passing a map of options would be a way of reducing the confusion? Additionally, what if I want to pass an MDC without a throwable? What if I want to log a throwable with no message? Etc.

**Comment by kumarshantanu** [comment]
@devn The Cambium API is modelled around the [tools.logging](https://github.com/clojure/tools.logging) API, adding the MDC argument and coalescing the variadic string message arguments into one `message`. In most cases you might need only the `info`, `error`, `debug` macros though, which expose the `[msg] [mdc msg] [mdc throwable msg]` arities.

However, I'm open to adding a saner API. :-) Please share your thoughts on how the new API should look like.

[SLF4j](https://www.slf4j.org/), on which Cambium is based, requires a message argument for logging. So, it must be inferred as a string if not supplied by the caller.

**Comment by devn** [comment]
Hey @kumarshantanu thanks for the reply. To be honest, I don't have a firm opinion here and would defer to your judgement, all I can say is that people I've worked with in the past that found it somewhat confusing, and I had a hard time disagreeing.

If I recall, I think the main gripe was around being forced to pass MDC when passing a throwable and a message. Most of the stuff we did with MDC was wrapped with a logging context, so there are a lot of `(log/error {} (Exception. "boom") "Something went boom.")` lines.

I can imagine something like this:
```clojure
(log/error {:mdc {:a 1} :msg "hello" :ex (Exception. "boom")})
```
Internally, then, cambium would choose the correct arity.

```clojure
(log/error {:msg "hello" :ex (Exception. "boom")})
```
would still call the same `[mdc throwable msg]` arity, but would pass {} as MDC on your behalf.

Perhaps this is all too magic. I have to say I don't really love passing the map, but it's one potential way of removing positionals that are often empty. Curious to hear if you have any other ideas.

Cheers,
Devin

**Comment by kidpollo** [comment]
I personally would prefer ` [msg] [msg mdc] [msg throwable mdc]` Conceptually the log message always have to be there with additional data that then gets processed to my log aggregator.

Additionally what I recommend my teams now is to always write their logging namespace and wrap whatever log api the want to use because all the logging libs out there have different signatures..

I also like to write custom macros to do things like

```clj
(log/mdc-context {:attr1 "all logging in here has this attr"}
    (log/info "foo" {:attrr2 "only this entry has attr2"})
)
```

**Comment by kumarshantanu** [comment]
I'm adding a backward-compatible arity overload (for the macros `info`, `error` etc.) as follows:

Old: `[msg] [mdc msg] [mdc throwable msg]`
New: `[msg-or-throwable] [mdc-or-throwable msg] [mdc throwable msg]`

I hope this takes care of some of the concerns that @devn raised. One of the constraints Cambium honors is low-overhead for its implementation. I guess one could write wrapper macros around Cambium's API for dynamic features and incompatible arity as @kidpollo mentioned.
